project:
  type: website
  output-dir: docs

website:
  title: "Workshop: Effective Graphics for Visual Communication with Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Materials
        menu:
          - "content/00-Setup.qmd"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib


