project:
  type: website
  output-dir: docs
  preview:
    port: 7777

execute:
  cache: true
  freeze: auto  # re-render only when source changes

website:
  title: "Workshop: Effective Graphics for Visual Communication with Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Materials
        menu:
          - "content/contents.qmd"
          - "content/00-Setup.qmd"
          - "content/01-Fundamentals.qmd"
          - "content/02-eda.qmd"
          - "content/03-accessibility.qmd"
          - "content/04-rules.qmd"
          - "content/05-workshop.qmd"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib


