---
title: "Workshop: Effective Graphics for Visual Communication with Data"
---

## Schedule

This schedule is highly tentative and subject to change at this time.

+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Time             | Title                                                                  | Description                                                                                                                                                                                                                      |
+==================+========================================================================+==================================================================================================================================================================================================================================+
| 8:30 - 9:00 AM   | [Introductions and Setup](content/00-Setup.qmd)                        | Instructors and students introduce themselves and get computers set up.                                                                                                                                                          |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9:00 - 10:45 AM  | [Fundamentals of Graphical Communication](content/01-Fundamentals.qmd) | The interaction between cognitive processes and graphics: how do we ensure people can read our charts?\                                                                                                                          |
|                  |                                                                        | [Slides](slides/01-Fundamentals.qmd "Fundamentals of Graphical Communication Slides")                                                                                                                                            |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:45 - 11:00 AM | Break                                                                  |                                                                                                                                                                                                                                  |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 12:00 PM | [Exploratory Data Analysis](content/02-eda.qmd)                        | Strategies for using graphics to generate insight about new data through rapid iteration.\                                                                                                                                       |
|                  |                                                                        | [Slides](slides/02-eda.qmd "Exploratory Data Analysis slides")                                                                                                                                                                   |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12:00 - 1:00 PM  | Lunch                                                                  |                                                                                                                                                                                                                                  |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1:00 - 2:45 PM   | [Accessibility: more than just alt-text](content/03-accessibility.qmd) | Accessibility guidelines applied to graphics. We will discuss color contrast rules, ways to help make graphics accessible to colorblind individuals, those with vision acuity loss, and those who use screen readers.\           |
|                  |                                                                        | [Slides](slides/03-accessibility.qmd "Accessibility slides")                                                                                                                                                                     |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2:45 - 3:00 PM   | Break                                                                  |                                                                                                                                                                                                                                  |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3:00 - 3:20 PM   | [The Rules... and when to break them](content/04-rules.qmd)            | We've spent the day up to this point discussing tactics for creating good data visualizations, but sometimes, the rules get in the way of effective communication with a specific audience. When is it ok to break these rules?\ |
|                  |                                                                        | [Slides](slides/04-rules.qmd "Rules slides")                                                                                                                                                                                     |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3:20 - 3:30      | Break                                                                  |                                                                                                                                                                                                                                  |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3:30 - 5:00 PM   | [Workshop: Improving our graphics](content/05-workshop.qmd)            | Working individually or in groups, we will improve existing graphics in order to apply the ideas in this workshop. Individuals can bring their own graphics to workshop or use graphics we've provided.                          |
+------------------+------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
