- file: construction_site.jpg
  url: https://www.flickr.com/photos/lhanaphotography/6107639393
  license: Image by Max and Dee Bernt, licensed as CC BY 2.0 Deed (https://creativecommons.org/licenses/by/2.0/)
